### ISSUE TITLE
Требования к внешнему интерфейсу от сервера ☃️

### ISSUE THREAD

**Issue by vladshcherbin** [LaravelRUS/laravel.ru#72]
Нужные плюшки с бэкэнда (в порядке важности в каждом разделе):

- [x] GraphQl
  - [x] Не работают переменные в запросах 
  - [x] Добавить поле `slug` в тип `article`
  - [x] Добавить возможность выбрать документацию какой-то конкретной версии `docs(version: String)`
  - [x] Добавить возможность выбрать страницу документации какой-то версии (сейчас можно выбрать только массив старниц)
  - [x] Изменить пагинацию на курсоровую https://github.com/LaravelRUS/laravel.ru/issues/68
  - [x] Добавить возможность выбирать несколько `articles` по `id` https://github.com/LaravelRUS/laravel.ru/issues/71
- [x] Api запросы
  - [x] Регистрация пользователя
  - [x] Авторизация пользователя
- [ ] Остальное
  - [ ] Селект в выборках GraphQl выбирает все поля, независимо от того, какие были запрошены https://github.com/LaravelRUS/laravel.ru/issues/71

**Comment by SerafimArts** [comment]
А можно ли это как-то отдельными задачами? 

...Не, ну могу кидать ссылки на коммиты просто сюда. Лови: https://github.com/LaravelRUS/laravel.ru/commit/6f3b9a4c36f8d1896477904f999ba3306f47fb2a

**Comment by vladshcherbin** [comment]
@SerafimArts а ты просто галочки ставь, я там в коммитах в любом случае найду 😉

**Comment by SerafimArts** [comment]
Cursor https://github.com/LaravelRUS/laravel.ru/commit/df9ab33fb2c8143a2d6d611d04ef65c9389187a6

**Comment by SerafimArts** [comment]
Several ids https://github.com/LaravelRUS/laravel.ru/commit/66d75b835123f22debb23e37ce8b22d0f1899797

**Comment by vladshcherbin** [comment]
Экономию на спичках с селектами оставим на потом.
